/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsAndCancellationPolicyRouteImport } from './routes/terms-and-cancellation-policy'
import { Route as ApiEnquiryRouteImport } from './routes/api/enquiry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndCancellationPolicyRoute =
  TermsAndCancellationPolicyRouteImport.update({
    id: '/terms-and-cancellation-policy',
    path: '/terms-and-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEnquiryRoute = ApiEnquiryRouteImport.update({
  id: '/api/enquiry',
  path: '/api/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-cancellation-policy': typeof TermsAndCancellationPolicyRoute
  '/api/enquiry': typeof ApiEnquiryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-cancellation-policy': typeof TermsAndCancellationPolicyRoute
  '/api/enquiry': typeof ApiEnquiryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-and-cancellation-policy': typeof TermsAndCancellationPolicyRoute
  '/api/enquiry': typeof ApiEnquiryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-cancellation-policy'
    | '/api/enquiry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-cancellation-policy'
    | '/api/enquiry'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-and-cancellation-policy'
    | '/api/enquiry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsAndCancellationPolicyRoute: typeof TermsAndCancellationPolicyRoute
  ApiEnquiryRoute: typeof ApiEnquiryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-cancellation-policy': {
      id: '/terms-and-cancellation-policy'
      path: '/terms-and-cancellation-policy'
      fullPath: '/terms-and-cancellation-policy'
      preLoaderRoute: typeof TermsAndCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enquiry': {
      id: '/api/enquiry'
      path: '/api/enquiry'
      fullPath: '/api/enquiry'
      preLoaderRoute: typeof ApiEnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsAndCancellationPolicyRoute: TermsAndCancellationPolicyRoute,
  ApiEnquiryRoute: ApiEnquiryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
